### ISSUE TITLE
How to expand scope after initial auth?

### ISSUE THREAD

**Issue by bitofbreeze** [sergiodxa/remix-auth-github#19]
I would like a user to be able to initially authenticate with GitHub with minimum scopes and then within my app click to grant the ones they want so that it is not all or nothing. Is there a good strategy for this?

Similar to these questions:
* https://github.com/nextauthjs/next-auth/issues/4726
* https://github.com/pennersr/django-allauth/issues/381

So far, all I can think of is making a second instance of GitHubStrategy with the expanded scopes, and then have an action that logs out the user and then logs back in using that strategy, but it would be optimal to not have to log them out because logging out (`await authenticator.logout(request, { redirectTo: "/" });`) redirects and then we will redirect again on login, so it is a bit messy for the dev and user.

**Comment by philipp-spiess** [comment]
I would also be interrested in this use case! Ideally without creating a second `GitHubStrategy` but instead having a way to define the scope dynamically (and get it passed thorugh as context to the strategy callback).

I think this would also need a second authenticator API as the current one will not forward you to the oauth redirect if the user is already logged in. 

So something like this maybe?

```ts
authenticator.addProvider(params.provider!, request, {
    successRedirect: "/app",
	scope: 'some-custom-scope'
 });
```

**Comment by sergiodxa** [comment]
Latest version of the package doesn't stop the auth flow if the user is already authenticated, so you can now trigger the flow again with the new scopes and that will send the user to GitHub as long as `?code` is not in the URL.
