### ISSUE TITLE
Support for GitHub App Auth?

### ISSUE THREAD

**Issue by bitofbreeze** [sergiodxa/remix-auth-github#20]
It seems like this package only supports authentication for GitHub OAuth but there is also GitHub App authentication, which then can be piggybacked on for [GitHub App Installation authentication](https://github.com/octokit/auth-app.js/#authenticate-as-installation). An example of this in use is when you connect repos to a Vercel account and it lets you select which repos to give access to. This is not possible with simple GitHub OAuth authentication. Would love it if this could be supported.

**Comment by sergiodxa** [comment]
Latest version should work with GitHub Apps and OAuth apps as per the [upstream client documentation](https://arcticjs.dev/providers/github).
