### ISSUE TITLE
Support GitHub App with OAuth

### ISSUE THREAD

**Issue by chris-feist** [sergiodxa/remix-auth-github#26]
GitHub allows apps to optionally add OAuth during the app installation, see [step 11 here](https://docs.github.com/en/apps/creating-github-apps/registering-a-github-app/registering-a-github-app). In this case, your callback URL is called directly after a user installs the app on GitHub.com with an auth code to exchange for a user token. However, this library fails to handle this because there is no state ([relevant code](https://github.com/sergiodxa/remix-auth-oauth2/blob/main/src/index.ts#L176)). Below example url signature for this scenario. 

Please add support for this auth flow!

```
http://localhost:3000/auth/github/callback?code=01234567890abcdef012&installation_id=01234567&setup_action=install
```

Debug error in console: `OAuth2Strategy State from URL null`

**Comment by sergiodxa** [comment]
Latest version should work with GitHub Apps and OAuth apps as per the [upstream client documentation](https://arcticjs.dev/providers/github).
