### ISSUE TITLE
Property 'scope' in type 'GoogleStrategy<User>' is not assignable to the same property in base type 'OAuth2Strat.....

### ISSUE THREAD

**Issue by xdivby0** [sergiodxa/remix-auth-github#27]
https://github.com/sergiodxa/remix-auth-github/blob/fdb212ae8910f78c8b647529b435a8d41b47c3c9/src/index.ts#L144

[The above line](https://github.com/sergiodxa/remix-auth-github/blob/fdb212ae8910f78c8b647529b435a8d41b47c3c9/src/index.ts#L144) gets marked by tsc and I see why it would do that - the superclass (OAuth2Strategy) has `scope?: string`. 

How does nobody else complain though, did I do something wrong (I copied this to modify for my own needs / other provider).

**Comment by sergiodxa** [comment]
This should be fixed in [v1.7.0](https://github.com/sergiodxa/remix-auth-github/releases/tag/v1.7.0)
