### ISSUE TITLE
Update to support Remix v2

### ISSUE THREAD

**Issue by JeffC25** [sergiodxa/remix-auth-github#29]
The package.json remix-auth lists @remix-run/react": "^1.0.0 || ^2.0.0" as a peerDependency, while remix-auth-github only lists "^1.0.0". This makes it incompatible with Remix v2.

**Comment by sergiodxa** [comment]
I would accept a PR to update the peer dependencies to include v2. [If this is blocking your company I can prioritize it](https://github.com/sponsors/sergiodxa/sponsorships?sponsor=sergiodxa&tier_id=320258&preview=false).
